### ISSUE TITLE
Should 0.20.0 in the `CHANGELOG` be 0.19.1?

### ISSUE THREAD

**Issue by ErichDonGubler** [Peternator7/strum#103]
A 0.20.0 version hasn't been published to https://crates.io, but there is an undocumented 0.19.1 version published there. The associated commit (9508a31) seems to be the fix described in the 0.20.0 entry in the `CHANGELOG`. So, a typo maybe?

**Comment by Peternator7** [comment]
I think you are correct. I appears there's a regression in 19.1 so expect a new patch version shortly anyway

**Comment by Peternator7** [comment]
Fixed in CHANGELOG.md. Version 0.19.2 is out now as well
