### ISSUE TITLE
Panic when using dotted access syntax in attributes (regression from 0.18 to 0.19.1)

### ISSUE THREAD

**Issue by Veetaha** [Peternator7/strum#104]
The new `0.19.1` version of `strum_macros` panics when reaches the dot operator expression in attributes metadata which might be used by `snafu` macros for example (see reproduction in the end).

The error message is so unhelpful that to understand where the bug comes from one needs clone this repo
and do a binary search with synthetically inserting `panic!("Here")` in code here and there.

<details>
<summary> The error message </summary>

```
error: proc-macro derive panicked
  --> crates/foo/src/main.rs:10:10
   |
10 | #[derive(IntoStaticStr)]
   |          ^^^^^^^^^^^^^
   |
   = help: message: called `Result::unwrap()` on an `Err` value: Error("expected `,`")
```

</details>

At the end of the day the panic comes from `syn` on this line of code:
https://github.com/Peternator7/strum/blob/a11862cebb3c69fc67db554bb264134932c55a4c/strum_macros/src/helpers/has_metadata.rs#L14

Change that `unwrap()` to `expect("Boom")` to check that this really is the place of panic.

Reproduction (panics on `0.19.1` of `strum_macros`, but version `0.18.0` works fine): 
```rust
use snafu::Snafu; // "0.6.8"
use strum_macros::IntoStaticStr;

#[derive(Debug)]
struct Inner {
    foo: &'static str
}

#[derive(Debug, Snafu)]
#[derive(IntoStaticStr)] // if you comment out this line, the crate compiles well
enum Error {
    #[snafu(display("Inner: {}", inner.foo))] // inner.foo syntax causes the panic (probably the dot)
    A {
        inner: Inner
    }
}

fn main() {
    dbg!(Error::A { inner: Inner { foo: "bar" } });
}
```

cc https://github.com/Peternator7/strum/pull/100

**Comment by Peternator7** [comment]
Should be fixed by #105. Can you verify locally?

**Comment by Veetaha** [comment]
Yup, with #105 there is no panic

**Comment by Peternator7** [comment]
PR is merged, and crate is published. 0.19.2 should fix this issue.

**Comment by Veetaha** [comment]
Great, thanks!
