### ISSUE TITLE
Travis CI not running?

### ISSUE THREAD

**Issue by jplatte** [Peternator7/strum#108]
Justing doing a small dependency audit, I noticed your recent commits only have sucessful AppVeyor checks, not Travis, despite a `.travis.yml` being present. Also, the Travis config tests for 1.26 when `README.md` says the MSRV is 1.31.

**Comment by jplatte** [comment]
@Peternator7 ping

**Comment by Peternator7** [comment]
I'm hoping to revisit the CI story and potentially switch to github actions, but I just haven't had time to. Since App Veyor is still running ,we're not at a total loss of coverage or anything so this just hasn't been the highest priority to update.
