### ISSUE TITLE
Convert to Rust edition 2018?

### ISSUE THREAD

**Issue by jplatte** [Peternator7/strum#109]
According to `README.md`, the MSRV for strum is 1.31, which is the version that introduced the 2018 edition. Would a PR updating the code base to the new edition be welcome?

**Comment by Peternator7** [comment]
Yes, I'd be open to that. Is there a motivating feature to the switch?

**Comment by jplatte** [comment]
Nothing serious, no. But it should be easier for people who aren't used to 2015's module system to contribute after the switch.

**Comment by Peternator7** [comment]
That's fair. I'd be open to a PR
