### ISSUE TITLE
no variant or associated item named `from_str`

### ISSUE THREAD

**Issue by mlmarius** [Peternator7/strum#117]
Trying to use Strum in my project. 
My dependencies are
>strum = "0.19"
strum_macros = "0.19"

My versions are
> cargo 1.43.0 (2cbe9048e 2020-05-03)
release: 1.43.0
commit-hash: 2cbe9048efc5c904b33191d799f97dc4698debaa
commit-date: 2020-05-03

This is the begining of my file:

```rust
#![cfg_attr(debug_assertions, allow(dead_code, unused_imports))]
extern crate strum;
#[macro_use]
extern crate strum_macros;

use strum_macros::{Display, EnumString};
```

Later on I decorate my enum:

```rust
#[derive(EnumString, Debug, Display)]
pub enum RelayState {
    #[strum(serialize = "0")]
    Open,
    #[strum(serialize = "1")]
    Closed,
}
```

and later still I try to use from_str:

```rust
let state: RelayState = RelayState::from_str(state_string).unwrap();
```

But I get this error:
>  --> src/main.rs:55:45
   |
20 | pub enum RelayState {
   | ------------------- variant or associated item `from_str` not found here
...
55 |         let state: RelayState = RelayState::from_str(state_string).unwrap();
   |                                             ^^^^^^^^ variant or associated item not found in `RelayState`
   |

Can someone help me figure this out ?

**Comment by Peternator7** [comment]
Hi @mlmarius, one possibility is that the `FromStr` trait hasn't been imported. Could you see if this code works?

```rust
use std::str::FromStr;
let state: RelayState = RelayState::from_str(state_string).unwrap();
```

**Comment by mlmarius** [comment]
That was it! Thanks!

**Comment by tejasjadhav** [comment]
Just confirming, std::str::FromStr` has to be imported in the file where you would be using the `from_str` method, not where you define the `Enum`, correct?

**Comment by Peternator7** [comment]
That's correct @tejasjadhav
