### ISSUE TITLE
AsRefStr Keep/Rename/Remove 

### ISSUE THREAD

**Issue by Peternator7** [Peternator7/strum#123]
Evaluating the naming scheme and value of all the macros used in strum. Some are more or less redundant such as `ToString` now that `Display` exists. This is a tracking issue to solicit feedback about the usefulness of `AsRefStr` and whether it should be kept and if so, what it's name should be.

**Comment by jplatte** [comment]
I vote keep, no name change.

**Comment by linclelinkpart5** [comment]
I like this feature, having a helper to create static strings is very helpful. Perhaps the macro could be renamed to `EnumToStr`?

**Comment by jplatte** [comment]
IMHO the `Enum` prefix should not exist anywhere within strum. For the rare case where there would be a collision or you want to disambiguate, `derive(strum::AsRefStr)` would work and not be overly long. And a project that needs these a lot and really wants the prefix can also just do this at the crate root:

```rust
pub use strum::{
    AsRefStr as EnumAsRefStr, Display as EnumDisplay, // ...
};
```

**Comment by linclelinkpart5** [comment]
@jplatte That makes sense, I agree with not having `Enum` as a prefix. Maybe a better name could be just `AsStr`?

**Comment by jplatte** [comment]
I would expect an `AsStr` derive to add an inherent method `as_str`, as exists on `String` and a few other types in `std`. For `impl AsRef<str> for T`, `AsRefStr` seems like the best choice to me.
