### ISSUE TITLE
Display Keep/Rename/Remove

### ISSUE THREAD

**Issue by Peternator7** [Peternator7/strum#124]
Evaluating the naming scheme and value of all the macros used in strum. Some are more or less redundant such as `ToString` now that `Display` exists. 

This is a tracking issue to solicit feedback about the usefulness of `Display` and whether it should be kept and if so, what it's name should be.

**Comment by jplatte** [comment]
This is probably one of the most commonly-used macros from strum. I don't think there's any alternative names to consider for this one :)

**Comment by linclelinkpart5** [comment]
I vote to keep! I consider this as the allocating version of `AsRefStr`. Perhaps the names of the variant attrs (`serialize` and `to_string`) could be cleared up a little bit? I often confuse strum's `serialize` with serde's.

**Comment by jplatte** [comment]
Right, I think `strum(rename)` and `strum(rename_all)` as the only renaming attributes would be the way to go.
