### ISSUE TITLE
EnumCount Keep/Rename/Remove

### ISSUE THREAD

**Issue by Peternator7** [Peternator7/strum#125]
Evaluating the naming scheme and value of all the macros used in strum. Some are more or less redundant such as `ToString` now that `Display` exists. 

This is a tracking issue to solicit feedback about the usefulness of `EnumCount` and whether it should be kept and if so, what it's name should be.

**Comment by linclelinkpart5** [comment]
Haven't had a use case for this yet, but I imagine this is a helpful feature!

**Comment by Nioub** [comment]
I think this is an important feature missing from the main rust library, and I'm glad you've done it. The naming semms correct.
FTR I'm a beginner in rust and I currently have a use for `EnumCount`.

**Comment by nwsharp** [comment]
This is the primary reason I'm using strum. It allows me to statically map a discriminant-only enum to a bitset.

**Comment by alice-i-cecile** [comment]
I need this too: it allows me to generate the number of enum variants to store in an Array-allocated map-like structure.
