### ISSUE TITLE
EnumDiscriminants Keep/Rename/Remove

### ISSUE THREAD

**Issue by Peternator7** [Peternator7/strum#126]
Evaluating the naming scheme and value of all the macros used in strum. Some are more or less redundant such as `ToString` now that `Display` exists. 

This is a tracking issue to solicit feedback about the usefulness of `EnumDiscriminants` and whether it should be kept and if so, what it's name should be.

**Comment by linclelinkpart5** [comment]
This was one of my main use cases for looking into `strum` to begin with, and definitely my most used. I feel this one is a must-keep for me!

**Comment by seanpianka** [comment]
Perhaps just `Discriminants`? But yes please keep this 👍
