### ISSUE TITLE
EnumMessage Keep/Rename/Remove

### ISSUE THREAD

**Issue by Peternator7** [Peternator7/strum#128]
Evaluating the naming scheme and value of all the macros used in strum. Some are more or less redundant such as `ToString` now that `Display` exists. 

This is a tracking issue to solicit feedback about the usefulness of `EnumMessage` and whether it should be kept and if so, what it's name should be.

**Comment by linclelinkpart5** [comment]
Admittedly, I don't foresee myself ever using this one over `AsRefStr` or `Display`. I wouldn't miss this one if it were to be cut.
