### ISSUE TITLE
EnumVariantNames Keep/Rename/Remove

### ISSUE THREAD

**Issue by Peternator7** [Peternator7/strum#130]
Evaluating the naming scheme and value of all the macros used in strum. Some are more or less redundant such as `ToString` now that `Display` exists. 

This is a tracking issue to solicit feedback about the usefulness of `EnumVariantNames` and whether it should be kept and if so, what it's name should be.

**Comment by linclelinkpart5** [comment]
This seems helpful, though I haven't used it myself.

**Comment by Peternator7** [comment]
This one interacts nicely with crates like Clap and structopt. You can use it to get a reference to an array of allowed values for command line flags. 

I'm almost certain this one will be kept. The candidate names for the macro are:

- `VariantNames`
- `Variants`

**Comment by linclelinkpart5** [comment]
@Peternator7 That makes sense, seems like it'd be a big win in that use case, and I could see myself really appreciating that feature.
