### ISSUE TITLE
README is wrong about when impl Trait was stabilized.

### ISSUE THREAD

**Issue by rodrimati1992** [Peternator7/strum#139]
The readme claims that `impl Trait` was stabilized in Rust 1.31.0:

> Strum is compatible with versions of rustc >= 1.31.0. That's the earliest version of stable rust that supports impl trait

But it actually was stabilized in Rust 1.26.0:
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1260-2018-05-10
> [`impl Trait` is now stable allowing you to have abstract types in returns or in function parameters](https://github.com/rust-lang/rust/pull/49255). E.g. `fn foo() -> impl Iterator<Item=u8>` or `fn open(path: impl AsRef<Path>)`.

Example in godbolt:
https://rust.godbolt.org/z/1oqcej

**Comment by Peternator7** [comment]
Looks like you're correct. I believe 1.31 is rust 2018, and that's the actually reason for the MSRV.

Will accept a PR with the fix or change myself.

**Comment by rodrimati1992** [comment]
From looking at the dependencies, I discovered that [`syn` 1.0](https://crates.io/crates/syn/1.0.0) requires Rust 1.31.

> Version requirement: Syn supports rustc 1.31 and up.

I guess all that needs to change is the README, mentioning `syn`'s minimum supported Rust version.
