### ISSUE TITLE
Using variant names as literals rather than static str

### ISSUE THREAD

**Issue by austinclem1** [Peternator7/strum#143]
Just asking if this is possible, I'm using an enum to represent all sounds in a simple game. The enum looks something like this:
```
enum Sound {
        Hit,
        Whoosh,
}
```

And somewhere else I'm embedding the sound files in the executable by using:
```
include_bytes!("../assets/sounds/hit.wav")
include_bytes!("../assets/sounds/whoosh.wav")
```

What would be awesome is if I can use the variant names as a string literal to generate the correct file path to these sound files. I was trying to do something like this:
```
for variant in Sound::VARIANTS {
    load_sound(include_bytes!(concat!("../assets/sounds/", variant, ".wav")))
}
```
(for what it's worth I am using the snake-case serialization here)

I realize I'm probably missing the mark because this whole for loop isn't necessarily expanding at compile time, but that's another step to figure out I guess. My main question is can I use one of these variant names as a string literal, not a static str? Because the `concat!` macro only accepts literals as arguments. This is the error I get:
```
only literals (like `"foo"`, `42` and `3.14`) can be passed to `concat!()`
```
Thanks for this crate and any help 

**EDIT:**
Actually I had more luck using the [rust-embed crate](https://github.com/pyros2097/rust-embed)
rust-embed seems to be happy with `&str` file paths rather than needing string literals like `include_bytes!` does. Now I'm using strum to generate the proper file path based on enum variants, and then rust-embed can find the correct file
```
for variant in Sound::VARIANTS {
    let path = &format!("sounds/{}.wav", variant);
    let file = &Asset::get(path).ok_or(format!("Failed to get file: {}.wav", variant))?;
    sounds.push(load_sound(file)?);
}
```

Feel free to close this if the string literal issue is beyond the scope of this crate, it may be something that isn't doable in rust at the moment, thanks

**Comment by Peternator7** [comment]
Hi @austinclem1, I don't think this is doable in rust right now, but I'll leave it open in case someone else proves me wrong :)
