### ISSUE TITLE
Outdated documentation links in README

### ISSUE THREAD

**Issue by Spaceface16518** [Peternator7/strum#146]
The links to macros in the docs.rs documentation is outdated because the versions are linked manually.

Since "0.20" is used in the `Cargo.toml` snippet, it may be worth considering using "0.20" in the documentation links as well; docs.rs can resolve crate names just like `cargo` does. This will ensure that the links always point to the intended documentation version. You could also just use "*" if you don't care about keeping the docs.rs links in lockstep with the `Cargo.toml` snippet, as "*" will always point to the latest available version.

I'd be happy to submit a PR with this little change if this issue is assigned to me.

**Comment by Peternator7** [comment]
Thanks for pointing this out, I'd be happy to accept a fix :)
