### ISSUE TITLE
enum name as prefix to enum value

### ISSUE THREAD

**Issue by dzmitry-lahoda** [Peternator7/strum#155]
given
```rust
enum Foo {
   Bar,
}
```

I want to get
```
"FooBar"
```

so something like could work

``` rust
#[strum_prefix]
enum Foo {
   Bar,
}
```

**Comment by jayvdb** [comment]
This would be very helpful for replicating Python enums, which display as `Foo.Bar` for the above scenario.

**Comment by cayman-amzn** [comment]
Looks like https://github.com/Peternator7/strum/pull/296 may solve your use case

**Comment by Peternator7** [comment]
This should be solved like @cayman-amzn suggested
