### ISSUE TITLE
Broken documentation link on docs.rs

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [Peternator7/strum#156]
Hi!

Just found that a link in the documentation is broken. Link to the page with broken link: https://docs.rs/strum_macros/0.20.1/strum_macros/derive.EnumString.html

Check "See the Additional Attributes Section for more information on using this feature.". "Addition Attributes" leads to an unexisting link - https://docs.rs/strum_macros/0.20.1/strum/additional_attributes/index.html

Will be awesome, if you will fix it.

Thanks in advance!

**Comment by Peternator7** [comment]
This works in 0.21. Thanks for finding the issue.
