### ISSUE TITLE
strum_macros::Display not detected in IDE (IntelliJ)

### ISSUE THREAD

**Issue by david-bouyssie** [Peternator7/strum#158]
Hi there.

I'm using the IntelliJ IDE and I have an issue regarding the use of ```strum_macros::Display```.
While I'm able to compile and execute my rust code correctly, I have remaining errors displayed in the IDE like:
```MyEnum` doesn't implement `Display` (required by {})```.

Also the ```.to_string()``` conversion is not suggested automatically by the IDE.
It looks like the macro is not well interpreted by the IDE.
Is it something you already observed?

Thanks.

**Comment by jaskij** [comment]
JB Rust plugin in general doesn't seem to work with any sort of `#[derive]` macro. Little to do in the crate itself.

**Comment by Peternator7** [comment]
Closing this because I'm not aware of much that can be done from the crate itself.
