### ISSUE TITLE
Provide proc-macro alternative to enum_from_primitive!{..}

### ISSUE THREAD

**Issue by Boscop** [Peternator7/strum#16]
There should be a derive proc-macro alternative to the macro_rules [`enum_from_primitive!{..}`](https://github.com/andersk/enum_primitive-rs) because it doesn't play well with other such macros like [`custom_derive!{..}`](https://docs.rs/enum_derive/0.1.7/enum_derive/).

I think it would make sense to have it as part of this crate, because it already contains many useful derives for enums.

**Comment by Peternator7** [comment]
Closing old issues. This was actually implemented as `FromRepr` not too long ago
