### ISSUE TITLE
Feature Request: Support for nested enums in EnumIter

### ISSUE THREAD

**Issue by juliancoffee** [Peternator7/strum#188]
My personal use case for EnumIter is using it for tests where I cover every possible enum variant. And with nested enums, it becomes strange as instead of getting every possible variant EnumIter uses default values for non-trivial enum variants.
I understand that doing that will be hard without breaking backward compatibility and probably very tricky for the general case.

Maybe some attribute like #[flatten]?

```rust
#[derive(strum::EnumIter)]
enum Uwu {
    Much,
    Such,
}

#[derive(strum::EnumIter)]
enum React {
    Wow,
    #[strum::flatten]
    Reaction(Uwu),
}
```
And then result of collecting this iterator will be `[React::Wow, React::Reaction(Uwu::Much), React::Reaction(Uwu::Such)]`

**Comment by Peternator7** [comment]
Sorry this didn't get a response earlier. This is probably outside the scope of this project, unless you still have a need and are interested in implementing this. There isn't much semantic information available to Derives so it's difficult to know how many iterations the flattened enum will produce.
