### ISSUE TITLE
EnumIter is missing documentation

### ISSUE THREAD

**Issue by spease** [Peternator7/strum#19]
You can't `#[derive(EnumIter)]` with `#![deny(missing docs)]`

**Comment by Peternator7** [comment]
This should be fixed by #25. I'll close this thread when it's on crates.io.

**Comment by spease** [comment]
Cool thanks

**Comment by Peternator7** [comment]
Version 0.10.0 is on crates. Should be fixed 😊

**Comment by spease** [comment]
Thanks!
