### ISSUE TITLE
Deriving for a "remote" enum?

### ISSUE THREAD

**Issue by dbr** [Peternator7/strum#191]
In crateA I have an enum like this:
```rust
enum Action {
    AddString(String),
    AddNumber(i64),
    Etc(Vec<String>),
}
```

In crateB I need an enum like
```rust
#[derive(Eq, PartialEq, Clone, Copy)]
enum ActionNames {
    AddString,
    AddNumber,
    Etc
}
```
where I then need to implement some traits for the `ActionNames`

Previously I was just defining the `ActionNames` enum manually which is fine but tediuos and accident prone.. `EnumDiscriminants` is almost exactly what I need, except.. I can't see a way to use it for a enum defined in another crate - is this possible somehow?

**Comment by Peternator7** [comment]
Hi dbr; I don't think this is possible given how rust's macro system currently works. Rust macros only get syntactic information for the current type so it can't see what variants are on the remote `Action` type. Serde kinda supports this scenario, but it requires you "redefine" the remote type in your own crate, which is exactly what you're trying to avoid.

**Comment by dbr** [comment]
Ahh, I figured it wasn't possible but couldn't find an answer for exactly why, "macros only get syntactic information for the current type" makes sense!

I suppose there probably is some form of workaround like a macro on the `crateA::Action` enum which writes the variants somewhere, and the derive macro for `ActionNames` reads from this, but seems far too convoluted - I'll see if I can find another way around it (probably just using `EnumDiscriminants` in `crateA`, and implementing the traits in `crateB` on a `struct Wrapper(ActionNames);` wrapper might work well enough)

Thanks!
