### ISSUE TITLE
Strum not deserializing snake_case variants from db

### ISSUE THREAD

**Issue by Overdash** [Peternator7/strum#197]
I have the following code:

```rust
#[derive(EnumString, Display, Debug, Serialize, Deserialize, Copy, Clone, sqlx::Type)]
#[sqlx(type_name = "text")]
#[strum(serialize_all = "snake_case")]
pub enum ContentType {
    Post,
    #[strum(to_string = "deep_dive")]  // FIXME not deserializing 'deep_dive'
    DeepDive,
    Comment,
}
```

Entries from the database (via `sqlx`) are saved in snake_case. It seems Strum is only able to deserialize one-to-one matches, i.e. `DeepDive` and `Post` will deserialize successfully, but `deep_dive` and `post` (lowercase) will not. Why is this? 

I've tried to use `serialize_all`, `to_string`, `serialize`, nothing works. Even tried to wrap it around serde.

Any help?

**Comment by Peternator7** [comment]
Hi @Overdash,

A few questions:
- What version of rust are you using?
- What version of strum are you using?
- What method are you using to "from_string" ContentType?

This code works when I try it:

```rust
#[derive(EnumString, strum::Display, Debug, Copy, Clone, PartialEq, Eq)]
#[strum(serialize_all = "snake_case")]
pub enum ContentType {
    Post,
    DeepDive,
    Comment,
}

#[test]
fn content_type_serialize_all() {
    use std::convert::TryFrom;
    use std::str::FromStr;

    assert_eq!(ContentType::DeepDive, ContentType::from_str("deep_dive").unwrap());
    assert_eq!(ContentType::DeepDive, ContentType::try_from("deep_dive").unwrap());
}
```

**Comment by Overdash** [comment]
Hey thanks for the prompt response
Rust version: rustc 1.54.0 (a178d0322 2021-07-26)
Strum: 0.23.0
Strum Macro: 0.23.1

Not too sure which method is being called (using `sqlx` to automatic deserialize columns to structs) but getting this error:
` 'error occurred while decoding column "content_type": invalid value "deep_dive" for enum ContentType'`. It's possible SQLx is using .`into()` but not too sure.

**Comment by Overdash** [comment]
I just tried this with
`#[sqlx(rename_all = "snake_case")]` and it worked.
Seems it wasn't a Strum issue at all - just SQLx not playing nice with Strum.

Sorry for the non-issue :)
