### ISSUE TITLE
Provide changelog for strum_macros 0.23.1

### ISSUE THREAD

**Issue by passcod** [Peternator7/strum#199]
The [current Cargo.toml](https://github.com/Peternator7/strum/blob/0c80602333a1fb462034fae1562b8d4e71fbe717/strum_macros/Cargo.toml) in this repo shows the version as 0.23.0, and there's no changelog entry for the patch.

I take care of investigating every dependabot PR and [this one's](https://github.com/ryankurte/cargo-binstall/pull/76) _looks_ very odd! Eventually I decided it was _probably_ just https://github.com/Peternator7/strum/pull/192 with an unpushed versioning commit, but if you could just push that it would make it a lot more obvious :)

**Comment by Peternator7** [comment]
This had been sitting in my local branch, but it's available now. Thanks for the heads up.
