### ISSUE TITLE
Feature request: `serialize_all = "snake_case"`

### ISSUE THREAD

**Issue by TeXitoi** [Peternator7/strum#21]
It would be great to have a `serialize_all` feature à la serde `rename_all`. https://serde.rs/container-attrs.html

This crate may be interesting: https://crates.io/crates/heck

Maybe with a spec and some insight, I might try to do it myself if I found the time.

**Comment by Peternator7** [comment]
Makes a lot of sense! Let me think a little more about this feature, and I'll get back to you.

**Comment by azriel91** [comment]
Hiya, I'm also keen on having this feature; if I made it happen would you take it?

**Comment by Peternator7** [comment]
Available in strum [0.11.0](https://crates.io/crates/strum)
