### ISSUE TITLE
`AsRefStr` does not seem to return `&str`

### ISSUE THREAD

**Issue by rsalmei** [Peternator7/strum#210]
Hello,

I know it is odd and even impossible, but it does seem to return `str` 🤔 
I'm trying to make a test detect if all variants were included in test data, so I've used both `AsRefStr` and `EnumVariantNames`.
The code I came up with is this:

```rust
        let events = ...;
        // ensures the test fixture does contain all variants.
        use strum::VariantNames;
        DeviceEvent::VARIANTS.iter().for_each(|v| {
            assert!(
                events.iter().find(|e| v == e.event.as_ref()).is_some(),
                "Missing variant: {}",
                v
            )
        });
```

So, the variant name from `VARIANTS` I must compare with the one from `.as_ref()`, but this fails with:
```rust
error[E0277]: can't compare `&str` with `str`
   --> src/device_events/mod.rs:347:49
    |
347 |             .all(|v| events.iter().find(|e| { v == e.event.as_ref() }).is_some()));
    |                                                 ^^ no implementation for `&str == str`
    |
    = help: the trait `PartialEq<str>` is not implemented for `&str`
    = note: required because of the requirements on the impl of `PartialEq<&str>` for `&&str`
```

How weird is that!! How could `.as_ref()` return an Unsized `str`??
And even weirder:
- I didn't need to include `use std::convert::AsRef` as the docs say;
- It DOES work if I make the find: `v == &e.event.as_ref()`... 🤪

So, what is going on here? What is the correct way to use it?
Thanks.

EDIT: I think it is implied, but my enum is like this:
```rust
#[derive(Debug, strum::EnumVariantNames, strum::AsRefStr)]
pub enum DeviceEvent {
    ...
}
```
Using cargo as `strum = { version = "0.23", features = ["derive"] }`

**Comment by ratmice** [comment]
> ```rust
>     = note: required because of the requirements on the impl of `PartialEq<&str>` for `&&str`
> ```

I'd just say note this line on the bottom, it looks like `v` is an `&str` and the other a `&&str`, and the `&str == str` is autoderefing one layer of references from each side.

**Comment by rsalmei** [comment]
Hummm I see, thanks @ratmice!

But in that case, why does an additional & on the **right side** `v == &e.event.as_ref()` made it work?
Wouldn't that turn the comparison into a `&str == &&&str`?? 🤔

**Comment by ratmice** [comment]
I believe it's on the *left side*, so the additional `&` then turns into `&&str == &&str`

**Comment by rsalmei** [comment]
Yeah yeah, I realize it is what would make sense...

Ohhh right! Since it is `PartialEq<A> for B`, the assignment should be `b == a`, i.e. they are inverted!

OK, thank you!
