### ISSUE TITLE
Reconsider bumping minor version on backwards-compatible updates because it contradicts cargo's semver

### ISSUE THREAD

**Issue by Veetaha** [Peternator7/strum#213]
# Context
I'd like to remind how [specifying dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#caret-requirements) works in Cargo.toml.

When you specify a bare version e.g. `foo = "0.1"` , cargo prepends a caret operator by default and treats it as `foo = "^0.1"`.
According to the docs referenced higher cargo's caret operator treats 0 major version dependencies specially in such a way that it thinks that transition from 0.1.0 to 0.2.0 is a breaking change, that's why it can't deduplicate the dependency tree if there are multiple entries of the same 0-major version crate with different minor versions.

What this all means:
The minor version of the crates that have 0 major version shouldn't be incremented if there were no breaking changes in that update. You'd better make the crate have >0 major version or bump just the patch component, otherwise, this is a disruptive update of the minor version that requires explicitly updating version requirements in all of the crate's reverse dependencies due to cargo's special treatment of unstable 0-major version crates.

# Summary 
According to the changelog, version `0.24.0` of `strum` is backward-compatible with `0.23.1`, so it should've been `0.23.2` to prevent the disruption. There is no clean solution to fix the aftermath, so we'll just have to live with it. This issue is mostly FYI, to prevent sudden disruptions in future.

If I am mistaken and there indeed was a breaking change, then what was it?

**Comment by Peternator7** [comment]
Hi @Veetaha, thank you for bringing this document to my attention. I reviewed it and agree some of the releases may not be properly following the convention for pre-1.0 crates so I will keep that in mind in the future. `0.24` does add a method to `EnumMessage`'s trait definition which is a breaking change. I assume (almost) everyone using that trait is deriving it, so they won't notice which is why I didn't call it out in the Changelog, but `strum` itself took a breaking change and then I updated `strum_macros` version as well to keep the version in sync.

**Comment by Veetaha** [comment]
@Peternator7 that's a good point. Adding a new non-default-implemented method to a trait is indeed a breaking change.
There is no language-native way to restrict implementing public traits from dependent crates. However, if this is really desired we could use documentation that clearly states that implementing the trait manually is not intended/supported because that trait may be extended in the future with new methods without bumping the minor version of the crate (or major version, if the crate is `>=1.0.0 `).

Also, stating such a restriction gives us the benefit of gaining the invariant that we may rely on:
The trait is always implemented by our proc macros, so it can not behave in surprising ways (e.g. return `None` where `Some` is expected), which we can rely on.

This all lies in my assumption that `EnumMessage` trait is really intended only for deriving and not manual impl. 
Anyway, I think it is reasonable to state that restriction, because otherwise each smiling minor addition of new methods to the API results in a breaking change. And, there are already 24 incompatible versions of `strum` accumulated. 
For example in our application we have at least three different versions of `strum` compiled in (we track this via [`cargo-deny`](https://embarkstudios.github.io/cargo-deny/checks/bans/index.html)), which are `0.21`, `0.22`, `0.23`, just because the ecosystem needs a lot of time to bump the major dependencies updates.
E.g. I did this contribution https://github.com/cholcombe973/block-utils not so long ago, so I was a bit disappointed, that there is now a new breaking change in `strum`.

**Comment by Veetaha** [comment]
Anyway, let's not leave this issue hanging. My goal was just to deliver this information to you. You may decide to accept my recommendations around future-proofing the API or not. So you can close this as "information taken into account" =)

**Comment by Veetaha** [comment]
Anyway, I'm closing this...
