### ISSUE TITLE
Deserialise in camelCase mode

### ISSUE THREAD

**Issue by FrederickFrance** [Peternator7/strum#216]
Hi all

I understand how to create a new type from an enum, I notice that strum allows me to serialize this new type in camelCase but I haven't found any way to deserialize this type in camelCase.

Does anyone have a solution?

**Comment by Peternator7** [comment]
Hello @FrederickFrance, deserializing should use the same case-style that serialization uses. See [this test](https://github.com/Peternator7/strum/blob/9465cd5dbbdc38c3f2fa5edf4aeeed66f813038c/strum_tests/tests/from_str.rs#L74) for an example. If that doesn't work, would you mind sharing some code to repro the issue?
