### ISSUE TITLE
0.24.1 Yanked

### ISSUE THREAD

**Issue by Peternator7** [Peternator7/strum#227]
Following #226, version 0.24.1 has been yanked from crates.io. I will work on getting those features re-enabled - preferably as 0.24.2, but potentially as 0.25 if it can't be done easily. Thank you for understanding. I decided in this situation, the best case scenario was to yank the package before it was out long enough for people to take dependencies on the new features. 

Sorry for the inconvenience.

**Comment by Sytten** [comment]
@Peternator7 Are you sure its been yanked? It still shows as 0.24.1 and not 0.24.2

**Comment by Peternator7** [comment]
Only strum_macros needed to be updated so that might be the confusion. Strum is still 0.24.1 but it should use macros version 0.24.2.  Does that line up with what you're seeing?

**Comment by Sytten** [comment]
Yes I was confused, thanks for clarifying!
