### ISSUE TITLE
Enum iterators trigger lints which can't be easily silenced

### ISSUE THREAD

**Issue by Cerber-Ursi** [Peternator7/strum#229]
Consider the following code (from [this SO question](https://stackoverflow.com/questions/72710177/missing-copy-debug-traits-warnings-when-defining-enum-with-strum-traits-in-mac)):
```rust
#![warn(
    missing_copy_implementations,
    missing_debug_implementations,
)]

use strum::{Display, EnumIter, EnumString};

macro_rules! define_fruits {
    {$($fruit:ident -> $name:literal),* $(,)?} => {
        #[allow(
            missing_copy_implementations,
            missing_debug_implementations,
        )]
        #[derive(Display, EnumIter, EnumString, Clone, Copy, Debug)]
        pub enum Fruits {
            $(
                // #[strum(to_string = $name)]
                $fruit,
            )*
        }
    };
}

define_fruits! {
    Apple -> "green",
    Orange -> "orange",
}
```

It triggers both specified warnings, because generated `FruitsIter` does implement neither `Debug` nor `Copy`. The latter is understandable (copyable iterators are quite a footgun, to be honest), the former might probably be adjusted, but maybe this implementation being missing is reasonable too.

What's important, however, is that the user has no way to silence these warnings short of `allow`ing them for the whole module, since there's no way to place the attribute on the `derive`-generated structure. Probably `strum` wants to `allow` these (and possibly others) lints itself?

**Comment by Peternator7** [comment]
Thanks for point this out. Added the linked PR to address the issue. Ideally, the iter should implement debug, but agree that Copy is probably a footgun. Unfortunately adding a Debug impl could be a breaking change b/c someone may have manually implemented it so I'll save that change for a larger version update. We can fix this lint though with a minor change and allowing these 2 lints

**Comment by Peternator7** [comment]
`0.24.3` was published 2 weeks ago and silences these errors
