### ISSUE TITLE
Allow to get a EnumDiscriminants without consuming the value

### ISSUE THREAD

**Issue by stephanemagnenat** [Peternator7/strum#230]
Currently, `EnumDiscriminants` allows to get a `MyEnumDiscriminants` from a `MyEnum` using the `From` trait. That provides the `.into()` method that consumes the value of type `MyEnum`. However, in many use cases (and my current one), one has a complex enum passed by reference, from which one wishes to get a discriminant by value. This is currently not possible.

Can we add an additional method besides just implement the `From` trait, something like:
```rust
fn discriminant(v: &MyEnum) -> MyEnumDiscriminants
```
possibly with a different name to [avoid a conflict with the method in `std::mem`](https://doc.rust-lang.org/std/mem/fn.discriminant.html)?

**Comment by Peternator7** [comment]
Hello @stephanemagnenat, 

Thanks for bringing this up. EnumDiscriminants should also implement `From<'a MyEnum> for MyEnumDiscriminants`. Could you check on your end if you're seeing that? Overload resolution probably dictates it's invoked like `MyEnumDiscriminants::from(&my_enum)`

**Comment by stephanemagnenat** [comment]
Yes it works, thank you for the input!
