### ISSUE TITLE
feature request: AsRefStr using the discriminant as UTF-8

### ISSUE THREAD

**Issue by ericlagergren** [Peternator7/strum#247]
I have an enum like this:

```rust
#[repr(u32)]
enum Foo {
    ID = 0x44492323, // = ##ID
    HD = 0x44482323, // = ##HD
    [...]
}
```

The discriminant is four UTF-8 bytes. It would be nice to have an option to generate `AsRef<str>` using the discriminant interpreted as UTF-8 instead of using the type name.

**Comment by Peternator7** [comment]
Hi @ericlagergren, this seems like a somewhat niche use-case so I'm not sure it's a good fit for strum. Most people would likely use an attribute to change how a variant is serialized.

**Comment by ericlagergren** [comment]
thanks for considering it!
