### ISSUE TITLE
Create FromRepr trait?

### ISSUE THREAD

**Issue by TotalKrill** [Peternator7/strum#251]
I am using FromRepr to create a default instance of every variant. I am creating widgets for Egui using this, and need to be able to enumerate all variants to fill DropDown menus. 

While doing this, I noticed that FromRepr derive, only creates the function, but does not provide a trait for it, making it hard to use in generic structs. Is there any logic as to not have a FromRepr trait?

**Comment by Peternator7** [comment]
I think the problem was that traits don't currently support const modifiers and that was one of the motivating examples for the derive.

**Comment by TotalKrill** [comment]
Yeah, I saw when I tried to implement it. 

Would a compromise be to have either FromRepr trait, or implement FromReprConst, and if there is const modifier support in the future, merge the implementations?

**Comment by Butanium** [comment]
Is there a workaround for this ? I want to implement a trait for all my `FromRepr` enum but I'm struggling to find how to do it

**Comment by Butanium** [comment]
Ok I found a workaround implementing 
```rust
trait EnumFromRepr
where
    Self: Sized,
{
    fn from_repr(discriminant: usize) -> Option<Self>;
}
```
for all my enums like so: 
```rust
#[derive(FromRepr, EnumCount, Debug, Clone, Copy)]
enum PenaltyType {
    Linear,
    Quadratic,
    Exponential,
}
impl EnumFromRepr for PenaltyType {
    fn from_repr(discriminant: usize) -> Option<Self> {
        PenaltyType::from_repr(discriminant)
    }
}
```
This is a bit heavy in syntax as I have to do this 5 lines of code `impl EnumFromRepr` so I'd love to know if there is a shorter workaround!

**Comment by Peternator7** [comment]
Closing this because I still don't think it's possible. Can revisit if/when this feature lands in rust
