### ISSUE TITLE
is_* methods

### ISSUE THREAD

**Issue by MendyBerger** [Peternator7/strum#252]
I wrote a little derive macro that generates `is_*` methods for each enum variant, and I wonder if strum would be a good home for it. If so, I'll open a PR.

Example:
```rust
#[derive(Is)]
enum Foo {
    Bar {},
    Biz
}
```
The `Is` derive will add `is_bar()` and `is_biz()` methods, similar to `Option::is_some()`, `Option::is_none()`, `Result::is_ok()`, etc.

I think that:
```rust
if foo.is_bar() {
    ....
}
```
is a lot cleaner then:
```rust
if matches!(foo, Foo::Bar { .. }) {
    ....
}
```

Thoughts?

**Comment by Peternator7** [comment]
Hi @MendyBerger , that seems like a great fit for strum. If you're interested, I'd be happy to accept a PR. Let me know if I can help
