### ISSUE TITLE
Release next version

### ISSUE THREAD

**Issue by azriel91** [Peternator7/strum#27]
Hiya! Thanks for this awesome crate :tada:.
There are a number of fixes in `master` that help me along my quest :crossed_swords:.
Please could you release the crate :package:, or is there something that must first be done (like that open PR)?

**Comment by Peternator7** [comment]
Hey! Glad you like it. I need to write a few docs before I can publish the next version, but I've got some free time today so I'll try and get a new crate up this weekend :)

**Comment by Peternator7** [comment]
Version [0.10.0](https://crates.io/crates/strum_macros) is live on crates.io!

**Comment by azriel91** [comment]
Thank you very much!
