### ISSUE TITLE
Unwrap methods

### ISSUE THREAD

**Issue by MendyBerger** [Peternator7/strum#277]
In a similar spirit to #252, would it be helpful to add `unwrap` methods to enums for variants?

E.g. 
```rust
enum Foo {
    Simple,
    Single(bool),
    Double(i32, String),
    Named {
        a: u8,
        b: u16,
    }
}
```
We could add the following methods:
```rust
impl Foo {
    pub fn unwrap_single(self) -> bool;
    pub fn unwrap_double(self) -> (i32, String);
    
    // we can also add reference versions of these (because we can't assume that .as_ref() is implemented on Foo)
    pub fn unwrap_single_ref(&self) -> &bool;
    pub fn unwrap_double_ref(&self) -> (&i32, &String);
}
```
Adding unwrap to `Foo::Simple` doesn't make much sense as there's nothing to unwrap.
Adding unwrap to `Foo::Named` is not possible as we'd need a struct name to return, an we don't have one. (unless we add a new struct `FooNamed` with the same values as `Foo::Named`, but that would probably be a bit too much.)
But for variants with unnamed values it might be useful.

We could also add `unwrap_or`, `unwrap_or_else`, `unwrap_unchecked` methods.

**Comment by PokeJofeJr4th** [comment]
I wrote the rest of the comment before looking at the `is_*` methods. Given that those were ultimately added to Strum, I think these work well. I'll start a fork.

This is definitely possible, but I'm not sure how useful it would be. Consider the following pattern:
```rust
// vanilla rust
let Foo::Double(integer, string) = foo else { panic!() };
// using unwraps
let (integer, string) = foo.unwrap_double();

// vanilla rust
let Foo::Named{a, b} = foo else { panic!() };
// no way to do this with these unwraps
```

*I assume you meant that adding unwrap to `Foo::Simple` wouldn't make sense?*

**Comment by MendyBerger** [comment]
> I assume you meant that adding unwrap to Foo::Simple wouldn't make sense?

Good catch! I fixed my original comment.

**Comment by PokeJofeJr4th** [comment]
I also just had another idea that I'd like to be able to derive: a version of the `Result::ok` method for each variant to get an option.
```rust
impl Foo {
  pub fn single(&self) -> Option<bool> {
    match self {
      Self::Single(b) => Some(b),
      _ => None,
    }
  }
}
```
This would be useful in map methods, since you could pull all the variants out like this:
```rust
let vec: Vec<Foo> = vec![...];
let singles: Vec<bool> = vec.iter().map(Foo::single).collect();
```

**Comment by Peternator7** [comment]
I'm down for this change; let's just make sure we're happy with the names and number of different Derives that it's split into.
So right now, I think there's 2 different Derives, unwrap, and `try_unwrap` (which I'm thinking should be `try_as_`)

```rust
impl MyEnum {
    // #[derive(Unwrap)]
    fn unwrap_variant(self) -> Type {}
    fn unwrap_variant_ref(&self) -> &Type {} // For Copy types, this is probably not useful, but not sure what to do with that.
    fn unwrap_variant_mut(&mut self) -> &mut Type {}
    // It's probably reasonable to choose a "default" for unwrapping that gets to be just `unwrap`, but that could
    // be a later feature

    // #[derive(TryAs)]
    fn try_as_variant(self) -> Option<Type> {}
    fn try_as_variant_ref(&self) ->Option<&Type> {}
    fn try_as_variant_mut(&mut self) -> Option<&mut Type> {}
}
```

**Comment by MendyBerger** [comment]
@Peternator7 also:
`unwrap_variant_or`, `unwrap_variant_or_else`, `unwrap_variant_unchecked`,
`unwrap_variant_ref_or`, `unwrap_variant_ref_or_else`, `unwrap_variant_ref_unchecked`,
`unwrap_variant_mut_or`, `unwrap_variant_mut_or_else`, `unwrap_mut_variant_unchecked`.

Don't think we need all these for try as, since you can just use the Option methods on there.

**Comment by MendyBerger** [comment]
I know that I was the one to propose the unwrap methods in the first place, but after seeing the try_as methods, I'm not sure that they're still needed.
You can basically achieve the same result as `foo.unwrap_variant()` by doing `foo.try_as_variant().unwrap()`.
And by using `Option`'s unwrap methods, we get the other goodies like `unwrap_or`, `unwrap_or_else`, `unwrap_unchecked`, `expect`, without having to pay anything in compile time.

Thoughts? 

cc @Peternator7 @PokeJofeJr4th
