### ISSUE TITLE
typo in docs

### ISSUE THREAD

**Issue by Boscop** [Peternator7/strum#29]
https://github.com/Peternator7/strum/blob/b6e4e6615788ab5d958ba7bbedd2fb55a069c323/strum/src/lib.rs#L113-L117

Also the same type is in the Readme.

**Comment by jplatte** [comment]
What do you mean? Everything seems to be correct. The serialized form "redred" is set via `#[strum(serialize = "redred")]`.

**Comment by jplatte** [comment]
That comment is no longer found in any places it doesn't belong.
