### ISSUE TITLE
`EnumString` match with non-default variables

### ISSUE THREAD

**Issue by wangxiaoying** [Peternator7/strum#295]
Is this case supported?
```rust
// definition
pub enum MyEnum {
    Variable1(bool),
    Variable2(bool),
}

// test
let v = MyEnum::from_str("Variable2(true)");
```

Currently it only works for `MyEnum::from_str("Variable2")"` and it will generate `v` as the default value `MyEnum::Variable2(false)`. And for the above test, I get a VariantNotFound error.

**Comment by Peternator7** [comment]
Hi @wangxiaoying, this case isn't really supported, and I don't think there's a straightforward path to supporting it. There's the very limited case of `Variable(true)` that we could probably handle, but there's a huge number of formatting considerations that are all reasonable, but make this feature impractically large to support.

Sorry about that!
