### ISSUE TITLE
[Feature] Macro to Implement PartialEq<str>

### ISSUE THREAD

**Issue by wyatt-herkamp** [Peternator7/strum#303]
So I made a macro called [CompareStr](https://github.com/wyatt-herkamp/enum_helper/blob/master/macros/src/compare_str/mod.rs)

Basically it implements PartialEq<str> for the Enum.

```rust
#[derive(Debug, Clone, PartialEq, Eq, CompareToStr)]
pub enum OtherTypes {
    #[compare_str(equals["uuid::Uuid", "Uuid"])]
    UUID {
        format: UUIDFormat,
        version: UUIDVersion,
    },
    #[compare_str(equals["PathBuf", "Path"])]
    FilePath,
}
```
I would like to create a Pull Request to implement this concept into Strum. 

So I was wanting to ask if this is a feature people would like to see in Strum. I would add support for PHF if I made a PR.

**Comment by Peternator7** [comment]
While this is cool, I probably can't accept a PR for it at the moment. There's a handful of larger features that are in-progress, and as the only maintainer, the complexity of managing strum as new features get added continues to increase. It's a neat feature for sure, but I think it's somewhat niche and I probably can't support it properly at this point. Thanks for reaching out however!
