### ISSUE TITLE
`get_bool` and `get_int` in `EnumProperty` are undocumented and always return None

### ISSUE THREAD

**Issue by fritzrehde** [Peternator7/strum#313]
When looking at [`EnumProperty`'s documentation](https://docs.rs/strum/latest/strum/trait.EnumProperty.html) that `get_bool` and `get_int` both always returned `None`. 
My expectation of these way that I could set a bool in a property like so:
```rust
    #[strum(props(HideInHelp = "true"))]
    Variant,
```
and then I thought `"true"` would get parsed into a bool, and I could just check an `Option<bool>` with `get_bool` at runtime.
What I don't understand is why `get_bool` exists and always returns `None`. Is the feature not ready/implemented yet, and was accidentally added to the master branch? It should also probably be documented at least with a doc-string to prevent the confusion I ran into.
Thanks for the cool crate!

**Comment by Milo123459** [comment]
bump. i have just tried implementing this to no avail, so was wondering if @Peternator7 had anything to say?
