### ISSUE TITLE
Getting the discriminant from an enum variant

### ISSUE THREAD

**Issue by MiniaczQ** [Peternator7/strum#318]
I've been browsing through the documentation and issues and there seems to be no easy way to convert a variant to it's discriminative.

I'm not sure if I missed it (please let me know), but it probably should be a thing.

**Comment by Peternator7** [comment]
Are you trying to get the `usize` discriminant value or the named enum you get from `EnumDiscriminants`?

**Comment by MiniaczQ** [comment]
Given enum `Foo` and it's discriminant `FooDiscriminant` I'd like to perform `discriminant(&Foo) -> FooDistriminant`.

**Comment by Peternator7** [comment]
I see, you want:

```rust
FooDiscriminant::from(&my_enum);
```

You can add an inherent method if you'd like:

```rust
impl MyEnum {
     fn discriminant(&self) -> FooDiscriminant {
         FooDiscriminant::from(self)
     } 
}
