### ISSUE TITLE
Publish new release.

### ISSUE THREAD

**Issue by gibbz00** [Peternator7/strum#323]
Hi,

Wondering if it would perhaps be possible to publish a more up-to-date version of strum to crates.io? `iggy` current relies on #288, and is currently preparing a new release. https://github.com/iggy-rs/iggy/issues/576.

All the best,

**Comment by Peternator7** [comment]
Hey @gibbz00, I got your email and I'm working on it :) Trying to get through the backlog of PR's at the same time. I should have one out this week.

**Comment by gibbz00** [comment]
Thanks for your reply! No rush 😊 We were just a bit unsure how actively maintained strum was. But I'll let the other Iggy devs know that all is good ✌️

**Comment by Peternator7** [comment]
Published [strum](https://crates.io/crates/strum) version `0.26.0` that includes this feature. There's a few minor breaking changes, but it should be straightforward to upgrade if you hit any.

**Comment by gibbz00** [comment]
Thank you ♥️
