### ISSUE TITLE
AsRefStr documentation incorrectly states 'static ref is returned

### ISSUE THREAD

**Issue by DTrippe** [Peternator7/strum#326]
Just wanted to report that the [AsRefStr](https://docs.rs/strum/latest/strum/derive.AsRefStr.html) documentation is wrong. It claims it will create a static str reference, which doesn't seem to be true.

> Converts enum variants to &'static str.

The lifetime of the reference is tied to the lifetime of the instance itself. E.,g

```rust
#[derive(strum::AsRefStr, strum::IntoStaticStr)]
enum MyVariant {
    A
}

fn main() {
    // Compiles fine
    let variant_str: &'static str = {
        let my_variant = MyVariant::A;
        my_variant.into()
    };
    // Complains that my_variant is dropped while still borrowed
    let variant_str: &'static str = {
        let my_variant = MyVariant::A;
        my_variant.as_ref()
    };
}
```

Just feel the documentation could be more explicit, and direct people to [IntoStaticStr](https://docs.rs/strum/latest/strum/derive.IntoStaticStr.html)

**Comment by Peternator7** [comment]
Thank you for reporting this issue. Would you mind opening a PR to correct it?

**Comment by DTrippe** [comment]
Created a PR here: https://github.com/Peternator7/strum/pull/330

Closing this as a result.
