### ISSUE TITLE
Publish Git tags

### ISSUE THREAD

**Issue by Marcono1234** [Peternator7/strum#327]
Hello,
would it be possible to publish Git tags, at least for future release versions? Currently it seems this repository has no Git tags which makes it difficult to compare all changes between versions, in case you want more information than provided in the changelog.

Workaround:
Open the `.cargo_vcs_info.json` for the corresponding version, e.g. https://docs.rs/crate/strum/0.26.0/source/.cargo_vcs_info.json, and obtain the commit hash from there.

**Comment by Peternator7** [comment]
That should be doable. here's 0.26.1 to get started :) https://github.com/Peternator7/strum/releases/tag/v0.26.1

**Comment by Marcono1234** [comment]
Thanks a lot! Feel free to close this issue, unless you want to keep it open as kind of 'reminder' for future versions.
