### ISSUE TITLE
`IntoStaticStr` interprets `to_string` literally

### ISSUE THREAD

**Issue by blind-oracle** [Peternator7/strum#367]
Not sure if it was mentioned already, I couldn't find.

Given the following example:
```
#[derive(IntoStaticStr)]
enum B {
 var1
 var2
}

#[derive(IntoStaticStr)]
enum A {
 #[strum(to_string = "{0}")]
 var3(B)
 var4
}

let a: &'static str = A::var3(B::var1);
```

We get a static string with a `{0}` inside, so the `to_string` is used as-is w/o formatting.

I'm not sure if it's intended, but it would be nice to be able to construct static strings using some macro parameter to get `var1` in the end. Currently I have to revert to an allocating `EnumString` to overcome this. I'm not even sure macros would allow for such formatting, but let's try :)

**Comment by Peternator7** [comment]
@blind-oracle, `IntoStaticStr` doesn't work with format strings. At macro expansion, there's no information about types other than the annotated enum so even though `B` also derives `IntoStaticStr`, there's no easy way to know that in the context of `A`.

**Comment by blind-oracle** [comment]
@Peternator7 I thought as much, it just a bit confused me that `IntoStaticStr` used the `to_string` in *some* way, but not as intended. Thanks for the response!
