### ISSUE TITLE
How do I add  docstrings to discriminants?

### ISSUE THREAD

**Issue by fabianfreyer** [Peternator7/strum#41]
First of all, thanks for this crate!

I'm refactoring some code to use the discriminants and would like to keept the documentation and doctests on the discriminant enum. Is there any way I can do that?

**Comment by Peternator7** [comment]
@fabianfreyer , sorry for the slow reply on this. I need to confirm that `Syn` parses the docstrings then this should be implementable.

**Comment by Peternator7** [comment]
I ran a quick test to confirm the current behavior. Right now the docs are copied from the enum over to the EnumDiscriminants? That seems like a reasonable default behavior to me. Is that what you are expecting?

**Comment by fabianfreyer** [comment]
No, I'd specifically like to add different docstrings including examples to the `EnumDiscriminants`.

I agree that copying docs seems like a reasonable default behavior, - I guess the feature I'm asking for is an explicit way of overriding this default.

I haven't worked much with procedural macros before, but if you could help me come up with a nice design for this (an additional attribute maybe? I don't know), I could try to get my hands dirty with a PR :)
