### ISSUE TITLE
Can enum::count() be a const function?

### ISSUE THREAD

**Issue by ArekPiekarz** [Peternator7/strum#58]
When EnumCount was introduced, there was a [comment](https://github.com/Peternator7/strum/issues/15#issuecomment-372063212) that the count() function could be const once the required feature get stabilized in Rust. It seems to me it is possible now, but I'm not a Rust expert yet, so I could be wrong. What is your opinion of this?

As a side effect, this could get rid of the X _COUNT constants polluting the public namespace, but I don't know if you'd want to remove them due to backwards compatibility. However, according to semver, version 0.x.y does not provide any guarantees, so the users should not have any assumptions anyway.

**Comment by xoac** [comment]
I think in Rust 1.35 is still impossible 

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f57dce05c0bf5b244fb2f370ac810072

`rustc --explain E0379` say

> Trait methods cannot be declared `const` by design. For more information, see
[RFC 911].

[RFC 911]: https://github.com/rust-lang/rfcs/pull/911

**Comment by ArekPiekarz** [comment]
Thanks, I hope it gets implemented one day.
