### ISSUE TITLE
Minor version bump needed?

### ISSUE THREAD

**Issue by dodomorandi** [Peternator7/strum#62]
I noticed that the `EnumVariantNames` is shown in the `README` (and it is pretty useful!), but it is not available on the last release. Could a minor version bump be worth in order to use this feature in a stable release?

**Comment by DrSensor** [comment]
I also noticed that `serialize_all = "lowercase"` is not available in v0.15.0

**Comment by Peternator7** [comment]
Version `0.16` is out now :)
