### ISSUE TITLE
`serialize_all` should be "as-is"

### ISSUE THREAD

**Issue by oxalica** [Peternator7/strum#64]
[`rename_all` from `serde`](https://serde.rs/container-attrs.html#rename_all) accepts `kebab-case`, `camelCase`, `PascalCase`, etc. The option string is just written in what itself representing to.

But `serialize_all` accepts all options in snake case, like `kebab_case` or `shouty_snake_case`, which can be sometimes misleading.

I think we should accept and prefer `serde`-like option string, while the snake case options can still be used for compatibility, maybe with a warning.

**Comment by Peternator7** [comment]
This was fixed in `0.16`. I appear to have missed this issue. Sorry about that.
