### ISSUE TITLE
Publish v0.16.0

### ISSUE THREAD

**Issue by mandrean** [Peternator7/strum#69]
Hi,

Would be awesome if you could publish a `v0.16.0` of Strum to `https://crates.io/crates/strum`, as the latest version there is `v0.15.0` from March, which for example doesn't have `EnumVariantNames` (#56)

Right now I have to do this to get `EnumVariantNames` in my project:

```
[dependencies]
strum = { git = "https://github.com/Peternator7/strum", rev = "efed58502a40ac101691068bbc6c20a0b351f3fd" }
strum_macros = { git = "https://github.com/Peternator7/strum", rev = "efed58502a40ac101691068bbc6c20a0b351f3fd" }
```

(Also would be nice with tags in Github that corresponds to the releases on Crates.io.)

Thanks!

**Comment by mandrean** [comment]
@Peternator7 

![image](https://user-images.githubusercontent.com/4631744/64131471-14a52a80-cdc9-11e9-8096-b99eedd41786.png)

Actually I'm a bit blocked now in one of my own projejcts! What do you think, could you help a brother out and publish `v0.16.0`? 😄

**Comment by ahmed-masud** [comment]
Until he's published it, my suggestion would be to pull it in and use crates.io-patch

**Comment by mandrean** [comment]
@ahmed-masud Building locally is fine with `git` + `rev`. I've also gotten `[replace]` and `[patch.crates-io]` working locally (separately)

But are you sure that one can _publish_ a crate to Crates.io if the dependency is a replace or patch pointing at a git branch or revision?

I just couldn't get publishing working. I've tried all kinds of permutations, like:

```
[dependencies]
...
strum = "0.15.0"
strum_macros = "0.15.0"
url = "2.1.0"

[replace]
"strum:0.16.0" = { git = "https://github.com/Peternator7/strum", branch = "refactor" }
"strum_macros:0.15.0" = { git = "https://github.com/Peternator7/strum", branch = "refactor" }
```

and

```
[dependencies]
...
strum = "0.15.0"
strum_macros = "0.15.0"

[replace]
"strum:0.16.0" = { git = "https://github.com/Peternator7/strum", branch = "refactor" }
"strum_macros:0.15.0" = { git = "https://github.com/Peternator7/strum", branch = "refactor" }
```
```
[dependencies]
...
strum = "0.15.0"
strum_macros = "0.15.0"

[patch.crates-io]
"strum" = { git = "https://github.com/Peternator7/strum", branch = "refactor" }
"strum_macros" = { git = "https://github.com/Peternator7/strum", branch = "refactor" }
```

**Comment by Peternator7** [comment]
Hi Sebastian,

I'm hoping to get to this as soon as I get back from my honeymoon :)

Sorry for the delay. It's been a busy few weeks 😅

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mandrean** [comment]
Awesome 😄 Enjoy your honeymoon @Peternator7

**Comment by killercup** [comment]
Enjoy your honeymoon!

(Found this issue when I wanted to ask for a new release, too. Also: If you need someone to help you maintain this crate, let me know!)

**Comment by Peternator7** [comment]
@mandrean , Version 0.16 is published :)

**Comment by mandrean** [comment]
Awesome! Thanks 😄
