### ISSUE TITLE
screaming kebab case doesn't treat numbers as separate word?

### ISSUE THREAD

**Issue by Luro02** [Peternator7/strum#72]
The following code doesn't work as expected
```rust
#[derive(Display)]
#[strum(serialize_all = "SCREAMING-KEBAB-CASE")]
enum Example {
    Aes128
}

assert_eq!(Example::Aes128, "AES-128".to_string());
```
instead strum generates:
`"AES128"`

**Comment by Peternator7** [comment]
Thanks for reaching out! 

Strum delegates generating all of it's different cases to the [heck](https://github.com/withoutboats/heck) crate. While I agree that's unexpected, I'm hesitant to add special cases on top of that library. I might suggest reaching out on that repo and see if they'd take a fix in their crate.

Thanks!

**Comment by jplatte** [comment]
Might I suggest moving away from `heck`? It uses unicode word boundaries, which seems excessive for source code (I haven't seen anybody complain about serde's `rename_all` lacking support for `#[feature(non_ascii_idents)]` and I doubt anybody currently using strum needs that).

Maybe you could reuse [serde's implementation](https://github.com/serde-rs/serde/blob/9f331cc25753edd71ad7ab0ea08a430fefaa90e1/serde_derive/src/internals/case.rs) or coordinate a shared crate for this logic with them?
