### ISSUE TITLE
Join members of enum

### ISSUE THREAD

**Issue by hongquan** [Peternator7/strum#78]
Given that I have this enum:

```rust
enum SpecialSeries {
    DA,
    KT,
    LD,
}
```

Now  I want to build this string

```rust
"DA|KT|LD"
```

in order to use as pattern for RegEx. How should I code with `strum`? (I don't write Rust often and always forget things when I try to learn Rust again).

Thank you.

**Comment by Peternator7** [comment]
Hi @hongquan,

Sorry for the delay here. Here's what you'd be looking for. I'm getting ready to push a new release so `VARIANTS` is new in that.

```rust
#[derive(strum::EnumVariantNames)]
enum SpecialSeries {
    DA,
    KT,
    LD,
}

let joined = SpecialSeries::VARIANTS.join("|");
```
