### ISSUE TITLE
IntoEnumIterator should have a constraint on Iterator: Iterator<Item=Self>

### ISSUE THREAD

**Issue by Ten0** [Peternator7/strum#80]
`IntoEnumIterator` does not have a constraint on `Iterator: Iterator<Item=Self>.`
When writing generic code on any `IntoEnumIterator`, it forces us to write the very verbose:
```rust
where
	<Self as IntoEnumIterator>::Iterator: Iterator<Item = Self>,
```
though that behaviour could be enforced as it is [documented on the trait](https://docs.rs/strum/0.17.1/strum/trait.IntoEnumIterator.html).

We could avoid having to write this by adding an `Iterator<Item=Self>` bound on the associated type `Iterator` of `IntoEnumIterator`.

**Comment by Peternator7** [comment]
Simple and shouldn't break anyone unless they were manually implementing the trait on something other than an enum.

This was easy so I went ahead and added it to version `0.18.0`. [https://crates.io/crates/strum]
