### ISSUE TITLE
Is there a derive for `my_enum.is_my_enum_variant()`?

### ISSUE THREAD

**Issue by nerdrew** [Peternator7/strum#81]
I'd like to be able to derive functions for each variant: `is_variant1()`, etc. Much like `is_some()`, `is_none()`, `is_ok()`, etc.

Is that supported? Feature request-able?

**Comment by Peternator7** [comment]
That is not currently implemented, but it would definitely be doable! You are welcome to tackle it if you'd like :) . Otherwise I'll see if I can get to it when I have time.

**Comment by Peternator7** [comment]
This was actually added in #257
