### ISSUE TITLE
Derived Display doesn't handle width and alignment parameters

### ISSUE THREAD

**Issue by DenisKolodin** [Peternator7/strum#87]
For struct like:

```rust
#[derive(Display)]
enum Type {
    One,
    Two,
}
```

The call:

```rust
println!("_ {:<20} _", Type::One);
```

Will print:
```
_ One _
```

But this expected:

```
_ One                 _
```

**The workaround** today only to convert it to string first:

```rust
println!("_ {:<20} _", Type::One.as_ref()); // and derive `AsRefStr` for enum needed
```

**Comment by Peternator7** [comment]
I didn't realize those parameters were exposed. Are you interested in working on this? If not, I'm going to mark this as help-wanted, and see if someone wants to fix it more quickly than I can get around to it.

For anyone interested in working on this. `Display::fmt` takes a [`Formatter`](https://doc.rust-lang.org/std/fmt/struct.Formatter.html) argument that contains information about the requested padding and alignment. We need to add logic to read that and then pad the outputs accordingly before writing them.

**Comment by Peternator7** [comment]
I took a look into this over the weekend, and it's actually a pretty small fix. The fmt module exposes a method for formatting strings already so it was as easy as hooking into that. #95
