### ISSUE TITLE
Fmt with fill/alignment is not working with Display derived enums

### ISSUE THREAD

**Issue by Boscop** [Peternator7/strum#94]
Fmt with [fill/alignment](https://doc.rust-lang.org/std/fmt/#fillalignment) (e.g. `{:<20}`) is not working with `Display`-derived enums, instead it behaves like `{}`.

**Comment by Peternator7** [comment]
Apparently this is really easy to fix. #95

**Comment by Peternator7** [comment]
Fixed in `0.19.0` on crates.io. #101
