### ISSUE TITLE
State of release

### ISSUE THREAD

**Issue by Veetaha** [Peternator7/strum#98]
Hi all! As I see there hasn't been a release to crates.io for 5 months. At least adding a repository link would be helpful to publish (#90). Are there any blockers for a new release? If you feel you don't have time/motivation for maintaining the project I recommend sharing the right to push and release new versions of the crate to some contributors.
cc @Peternator7

**Comment by Peternator7** [comment]
Hi @Veetaha, thanks for the push. I think there's 2 changes sitting in master (one of which is the repo link you mentioned) so there hasn't been a huge urge, but I certainly can and should be better about pushing updates :)

I'll cut a new release this weekend and roll up any easy PR's as well.

**Comment by Veetaha** [comment]
Oh, cool, thanks, looking forward to it! :tada:

**Comment by Peternator7** [comment]
It took an extra week, but `0.19.0` is released on crates.io. #101
